#!/bin/bash

# Execute with: ./this-script $PrinterIds...
# Meaning, any number of space seperated numbers

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
printerIDs=( "$@" )

# Formats printer IDs with leading zeros
for i in ${!printerIDs[@]}
do
    printerIDs[$i]=`printf "%04d" ${printerIDs[$i]}`
done

# Initialize Printer ID lists and device files
ids="'${printerIDs[0]}'"
dev_files="'/dev/ttyUSB0'"

# Constructs the Lists of python strings for output
for i in `seq 1 $((${#printerIDs[*]} - 1))`
do
    ids="$ids, '${printerIDs[$i]}'"
    dev_files="$dev_files, '/dev/ttyUSB$i'"
done

OUT_FILE="$SCRIPT_DIR/cpprinter/printerinfo.py"

echo "class PrinterInfo:" > $OUT_FILE
echo "    PrinterIds = [$ids]" >> $OUT_FILE
echo "    PrinterPorts = [$dev_files]" >> $OUT_FILE

