#!/bin/bash

regex="^[[:digit:]]{4}$"

echo "What is this printer's ID? "
read id

while [[ ! $id =~ $regex ]]; do
    echo "Invalid Printer Id. Must be exactly 4 numbers."
    read id
done

sed -i "/PrinterId/c\    PrinterId = \"$id\"" cpprinter/cpdefs.py
